header:
  license:
    spdx-id: Apache-2.0
    copyright-owner: CloudWeGo Authors


  paths:
    - '**/*.go'
    - '**/*.s'
  paths-ignore:
    - example/prom/promWithkitex/kitex_gen/**
    - registry/**/kitex_gen/**
  comment: on-failure